### This code will
1. Connect the static data to the actual data we have
2.

In [37]:
# Getting the datasets
import pandas as pd
stop_times = pd.read_csv('Datasets/stop_times.txt', sep=',')
stops = pd.read_csv('Datasets/stops.txt', sep=',')
trips = pd.read_csv('Datasets/trips.txt', sep=',')
data = pd.read_csv('data/test3/bus_data_current_chicago.csv')
calendar = pd.read_csv('Datasets/trips.txt', sep=',')

/var/folders/y1/1zf0l7g530dd_mqbfll_qkhh0000gn/T/ipykernel_86349/1652522602.py:6: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('data/test3/bus_data_current_chicago.csv')

In [ ]:
trips.shape

In [38]:
merged = trips.merge(calendar, how='inner', on='service_id')

:

In [20]:
trips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49936 entries, 0 to 49935
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   route_id               49936 non-null  object
 1   service_id             49936 non-null  int64
 2   trip_id                49936 non-null  int64
 3   direction_id           49936 non-null  int64
 4   block_id               49936 non-null  int64
 5   shape_id               49936 non-null  int64
 6   direction              49936 non-null  object
 7   wheelchair_accessible  49936 non-null  int64
 8   schd_trip_id           49936 non-null  object
dtypes: int64(6), object(3)
memory usage: 3.4+ MB

In [24]:
data[data['rt'] == '6'].head()

,vid,tmstmp,lat,lon,hdg,pid,rt,des,pdist,dly,tatripid,origtatripno,tablockid,zone,mode,psgld,stst,stsd,pulled_at,rt_chunk
15,8475,20260219 23:41,41.888130,-87.622368,273,7107,6,79th/South Shore,2682,False,22224104,273988766,6 -164,NaN,1,NaN,85260,2026-02-19,2026-02-19 23:41:14 CST,"1,2,3,4,X4,N5,6,7,8,8A"
16,4053,20260219 23:40,41.878395,-87.627753,176,7107,6,79th/South Shore,7611,False,22224103,273988765,6 -163,NaN,1,NaN,84330,2026-02-19,2026-02-19 23:41:14 CST,"1,2,3,4,X4,N5,6,7,8,8A"
17,8498,20260219 23:40,41.811951,-87.590607,159,7107,6,79th/South Shore,35722,False,22224102,273988764,6 -161,NaN,1,NaN,83400,2026-02-19,2026-02-19 23:41:14 CST,"1,2,3,4,X4,N5,6,7,8,8A"
18,4083,20260219 23:41,41.773583,-87.586288,179,7107,6,79th/South Shore,51890,False,22224101,273988763,6 -158,NaN,1,NaN,82410,2026-02-19,2026-02-19 23:41:14 CST,"1,2,3,4,X4,N5,6,7,8,8A"
19,8001,20260219 23:40,41.751152,-87.544746,283,14134,6,Wacker/Columbus,499,False,22224106,273988909,6 -165,NaN,1,NaN,85170,2026-02-19,2026-02-19 23:41:14 CST,"1,2,3,4,X4,N5,6,7,8,8A"

In [21]:
trips['shape_id'] = trips['shape_id'].astype(str)
trips['trip_id'] = trips['trip_id'].astype(str)
trips['block_id'] = trips['block_id'].astype(str)

In [36]:
trips[(trips['route_id'] == '6') & (trips['shape_id'].str.contains('14134'))]

,route_id,service_id,trip_id,direction_id,block_id,shape_id,direction,wheelchair_accessible,schd_trip_id
4765,6,67709,6770021053010,1,677000005452,67714134,North,1,21053010
4766,6,67709,6770021209010,1,677000005451,67714134,North,1,21209010
4767,6,67709,6770021616010,1,677000004785,67714134,North,1,21616010
4768,6,67709,6770021736010,1,677000004794,67714134,North,1,21736010
4769,6,67709,6770022252010,1,677000004787,67714134,North,1,22252010
...,...,...,...,...,...,...,...,...,...
5080,6,67701,6770013250020,1,677000003054,67714134,North,1,13250020
5081,6,67701,6770013609020,1,677000004212,67714134,North,1,13609020
5082,6,67701,6770013818020,1,677000004207,67714134,North,1,13818020
5083,6,67701,6770014056020,1,677000004404,67714134,North,1,14056020
5084,6,67701,6770014187020,1,677000003287,67714134,North,1,14187020

In [4]:
stop_times.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2996069 entries, 0 to 2996068
Data columns (total 8 columns):
 #   Column               Dtype
---  ------               -----
 0   trip_id              int64
 1   arrival_time         object
 2   departure_time       object
 3   stop_id              int64
 4   stop_sequence        int64
 5   stop_headsign        object
 6   pickup_type          int64
 7   shape_dist_traveled  int64
dtypes: int64(5), object(3)
memory usage: 182.9+ MB

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 663 entries, 0 to 662
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   vid           663 non-null    int64
 1   tmstmp        663 non-null    object
 2   lat           663 non-null    float64
 3   lon           663 non-null    float64
 4   hdg           663 non-null    int64
 5   pid           663 non-null    int64
 6   rt            663 non-null    object
 7   des           663 non-null    object
 8   pdist         663 non-null    int64
 9   dly           663 non-null    bool
 10  tatripid      663 non-null    int64
 11  origtatripno  663 non-null    int64
 12  tablockid     663 non-null    object
 13  zone          0 non-null      float64
 14  mode          663 non-null    int64
 15  psgld         0 non-null      float64
 16  stst          663 non-null    int64
 17  stsd          663 non-null    object
 18  pulled_at     663 non-null    object
 19  rt_chunk      663 non-null    object
dtypes: bool(1), float64(4), int64(8), object(7)
memory usage: 99.2+ KB

In [6]:
stops.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11130 entries, 0 to 11129
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   stop_id              11130 non-null  int64
 1   stop_code            10675 non-null  float64
 2   stop_name            11130 non-null  object
 3   stop_desc            10522 non-null  object
 4   stop_lat             11130 non-null  float64
 5   stop_lon             11130 non-null  float64
 6   location_type        11130 non-null  int64
 7   parent_station       332 non-null    float64
 8   wheelchair_boarding  11130 non-null  int64
dtypes: float64(4), int64(3), object(2)
memory usage: 782.7+ KB

In [7]:
trips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49936 entries, 0 to 49935
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   route_id               49936 non-null  object
 1   service_id             49936 non-null  int64
 2   trip_id                49936 non-null  int64
 3   direction_id           49936 non-null  int64
 4   block_id               49936 non-null  int64
 5   shape_id               49936 non-null  int64
 6   direction              49936 non-null  object
 7   wheelchair_accessible  49936 non-null  int64
 8   schd_trip_id           49936 non-null  object
dtypes: int64(6), object(3)
memory usage: 3.4+ MB

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 663 entries, 0 to 662
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   vid           663 non-null    int64
 1   tmstmp        663 non-null    object
 2   lat           663 non-null    float64
 3   lon           663 non-null    float64
 4   hdg           663 non-null    int64
 5   pid           663 non-null    int64
 6   rt            663 non-null    object
 7   des           663 non-null    object
 8   pdist         663 non-null    int64
 9   dly           663 non-null    bool
 10  tatripid      663 non-null    int64
 11  origtatripno  663 non-null    int64
 12  tablockid     663 non-null    object
 13  zone          0 non-null      float64
 14  mode          663 non-null    int64
 15  psgld         0 non-null      float64
 16  stst          663 non-null    int64
 17  stsd          663 non-null    object
 18  pulled_at     663 non-null    object
 19  rt_chunk      663 non-null    object
dtypes: bool(1), float64(4), int64(8), object(7)
memory usage: 99.2+ KB

In [14]:
data['origtatripno'].sort_values(ascending=True)

513    273981786
221    273981786
511    273981787
219    273981787
512    273981788
         ...
309    274070187
60     274070256
190    274116844
374    274116844
650    274116844
Name: origtatripno, Length: 663, dtype: int64

In [15]:
trips['schd_trip_id'].sort_values(ascending=True)

3870     10000020
22396     1000010
8443       100010
4905     10001070
37025    10004070
           ...
253          R941
24804        R941
266          R941
427          R941
25338        R941
Name: schd_trip_id, Length: 49936, dtype: object

In [112]:
trips['schd_trip_id'] = trips['schd_trip_id'].astype(str)
data['tatripid'] = data['tatripid'].astype(str)

In [120]:
trips_ids = set(trips['schd_trip_id'].astype(str))
veh_orig = set(data['origtatripno'].astype(str))
print(trips_ids & veh_orig)

set()

In [ ]:
import pandas as pd
from datetime import datetime

# Load data
stops = pd.read_csv('Datasets/stops.txt')
trips = pd.read_csv('Datasets/trips.txt')
stop_times = pd.read_csv('Datasets/stop_times.txt')  # your stop_times data
vehicles = pd.read_csv('data/bus_data_current_chicago.csv')       # your bus tracker data

# Step 1: Link tatripid → trip_id via trips.schd_trip_id
trips['schd_trip_id'] = trips['schd_trip_id'].astype(str)
vehicles['tatripid'] = vehicles['tatripid'].astype(str)
trips['schd_trip_id_stripped'] = trips['schd_trip_id'].str.replace('020$', '', regex=True).str.lstrip('0')
# Then try merging on that vs tatripid

vehicles = vehicles.merge(
    trips[['trip_id', 'schd_trip_id', 'route_id']],
    left_on='tatripid',
    right_on='schd_trip_id',
    how='left'
)

# Step 2: Join stop_times to get scheduled stops for each trip
stop_times = stop_times.merge(stops[['stop_id','stop_name','stop_lat','stop_lon']], on='stop_id')

# Step 3: For each vehicle, find the NEXT scheduled stop
# (the first stop where shape_dist_traveled > vehicle's pdist)
def find_next_stop(row, st):
    trip_stops = st[st['trip_id'] == row['trip_id']].sort_values('shape_dist_traveled')
    next_stops = trip_stops[trip_stops['shape_dist_traveled'] >= row['pdist']]
    if next_stops.empty:
        return None
    return next_stops.iloc[0]

# Step 4: Compare scheduled arrival time vs current time
# Parse vehicle timestamp
vehicles['tmstmp'] = pd.to_datetime(vehicles['tmstmp'], format='%Y%m%d %H:%M')

# For each vehicle, get scheduled time at next stop and compute delay
# stop_times arrival_time is like "11:37:00" — convert to today's datetime for comparison
def get_delay_minutes(vehicle_time, scheduled_time_str):
    h, m, s = map(int, scheduled_time_str.split(':'))
    scheduled = vehicle_time.replace(hour=h, minute=m, second=s)
    return (vehicle_time - scheduled).total_seconds() / 60  # positive = late

KeyError: 'schd_trip_id_stripped'

In [119]:
vehicles.to_csv('vehicles.csv')

In [117]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 663 entries, 0 to 662
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   vid           663 non-null    int64
 1   tmstmp        663 non-null    object
 2   lat           663 non-null    float64
 3   lon           663 non-null    float64
 4   hdg           663 non-null    int64
 5   pid           663 non-null    int64
 6   rt            663 non-null    object
 7   des           663 non-null    object
 8   pdist         663 non-null    int64
 9   dly           663 non-null    bool
 10  tatripid      663 non-null    object
 11  origtatripno  663 non-null    int64
 12  tablockid     663 non-null    object
 13  zone          0 non-null      float64
 14  mode          663 non-null    int64
 15  psgld         0 non-null      float64
 16  stst          663 non-null    int64
 17  stsd          663 non-null    object
 18  pulled_at     663 non-null    object
 19  rt_chunk      663 non-null    object
dtypes: bool(1), float64(4), int64(7), object(8)
memory usage: 99.2+ KB

In [16]:
stop_times['stop_sequence'].sort_values(ascending=True)

2677479      1
936953       1
2133364      1
862218       1
1183184      1
          ...
1975453    127
964757     127
1399747    127
151423     127
2814007    127
Name: stop_sequence, Length: 2996069, dtype: int64

In [17]:
pd.merge(stop_times, trips, how='inner', on = 'trip_id')

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,shape_dist_traveled,route_id,service_id,direction_id,block_id,shape_id,direction,wheelchair_accessible,schd_trip_id
0,90271636492,11:37:00,11:37:00,30023,19,Midway,0,90717,Org,109009,1,90025678386,309000034,0,1,R701
1,90271636492,11:41:00,11:41:00,30061,20,Midway,0,101777,Org,109009,1,90025678386,309000034,0,1,R701
2,90271636492,11:43:00,11:43:00,30220,21,Midway,0,107301,Org,109009,1,90025678386,309000034,0,1,R701
3,90271636492,11:45:30,11:45:30,30186,22,Midway,0,113178,Org,109009,1,90025678386,309000034,0,1,R701
4,90271636492,11:48:00,11:48:00,30182,23,Midway,0,120102,Org,109009,1,90025678386,309000034,0,1,R701
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2996064,6770049230010,22:10:44,22:10:44,2596,99,115th,0,65188,4,67709,0,677000004544,67719379,South,1,49230010
2996065,6770049230010,22:11:30,22:11:30,2598,100,115th,0,66164,4,67709,0,677000004544,67719379,South,1,49230010
2996066,6770049230010,22:12:08,22:12:08,2821,101,115th,0,66828,4,67709,0,677000004544,67719379,South,1,49230010
2996067,6770049230010,22:12:32,22:12:32,2822,102,115th,0,67419,4,67709,0,677000004544,67719379,South,1,49230010
2996068,6770049230010,22:12:53,22:12:53,2823,103,115th,0,68171,4,67709,0,677000004544,67719379,South,1,49230010

In [94]:
data.head()

,vid,tmstmp,lat,lon,hdg,pid,rt,des,pdist,dly,tatripid,origtatripno,tablockid,zone,mode,psgld,stst,stsd,pulled_at,rt_chunk
0,7967,20260219 23:38,41.834482,-87.616959,3,18414,3,Michigan/Chicago,44274,False,398,273997116,3 -773,NaN,1,NaN,83040,2026-02-19,2026-02-19 23:38:59 CST,"1,2,3,4,X4,N5,6,7,8,8A"
1,1348,20260219 23:38,41.874847,-87.624176,358,18414,3,Michigan/Chicago,60293,False,88365493,273997115,3 -717,NaN,1,NaN,82020,2026-02-19,2026-02-19 23:38:59 CST,"1,2,3,4,X4,N5,6,7,8,8A"
2,8679,20260219 23:38,41.895270,-87.620338,1,18415,3,95th Red Line,804,False,88365629,273997232,3 -770,NaN,1,NaN,84840,2026-02-19,2026-02-19 23:38:59 CST,"1,2,3,4,X4,N5,6,7,8,8A"
3,8686,20260219 23:38,41.869291,-87.624184,181,18415,3,95th Red Line,12491,False,88365628,273997231,3 -709,NaN,1,NaN,84090,2026-02-19,2026-02-19 23:38:59 CST,"1,2,3,4,X4,N5,6,7,8,8A"
4,8901,20260219 23:38,41.850828,-87.619041,179,18415,3,95th Red Line,20431,False,1080329,273997230,3 -775,NaN,1,NaN,83340,2026-02-19,2026-02-19 23:38:59 CST,"1,2,3,4,X4,N5,6,7,8,8A"

In [28]:
set(data["tatripid"].astype(str)) & set(trips["schd_trip_id"])

set()

In [30]:
len(set(data["tatripid"]))

278

In [31]:

len(set(trips["schd_trip_id"]))

45211

In [35]:
data["tatripid"] = data["tatripid"].astype(str)
trips["trip_id"] = trips["trip_id"].astype(str)
trips["schd_trip_id"] = trips["schd_trip_id"].astype(str)
stop_times["trip_id"] = stop_times["trip_id"].astype(str)

data["tablockid"] = data["tablockid"].astype(str)
trips["block_id"] = trips["block_id"].astype(str)

data["rt"] = data["rt"].astype(str)
trips["route_id"] = trips["route_id"].astype(str)

In [36]:
df = data.merge(
    trips,
    left_on=["tablockid","rt"],
    right_on=["block_id","route_id"],
    how="left"
)

In [37]:
df.head()

,vid,tmstmp,lat,lon,hdg,pid,rt,des,pdist,dly,...,rt_chunk,route_id,service_id,trip_id,direction_id,block_id,shape_id,direction,wheelchair_accessible,schd_trip_id
0,7967,20260219 23:38,41.834482,-87.616959,3,18414,3,Michigan/Chicago,44274,False,...,"1,2,3,4,X4,N5,6,7,8,8A",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1348,20260219 23:38,41.874847,-87.624176,358,18414,3,Michigan/Chicago,60293,False,...,"1,2,3,4,X4,N5,6,7,8,8A",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,8679,20260219 23:38,41.895270,-87.620338,1,18415,3,95th Red Line,804,False,...,"1,2,3,4,X4,N5,6,7,8,8A",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,8686,20260219 23:38,41.869291,-87.624184,181,18415,3,95th Red Line,12491,False,...,"1,2,3,4,X4,N5,6,7,8,8A",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8901,20260219 23:38,41.850828,-87.619041,179,18415,3,95th Red Line,20431,False,...,"1,2,3,4,X4,N5,6,7,8,8A",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN